SUMMARY = "Extended Type Hinting Support"
DESCRIPTION = " \
* Functions for thorough checks on types \
* Instance checks considering generics \
* Typesafe Duck-typing \"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=de6d7dd24be15cc00bdfd9714f4929b3"

SRC_URI = "https://files.pythonhosted.org/packages/48/10/84e80246203f017fd27559b49557753d96cee860754247b7b023fd03d236/typish-1.9.1-py3-none-any.whl"

SRC_URI[md5sum] = "52ea7bfd6bd818d9ab11bb1a78128650"
SRC_URI[sha256sum] = "017095ef9a3570c6ec334497eb2e03bad4e61873e50c41fe59e3c73b24090359"

PYPI_PACKAGE = "typish"
PYPI_PACKAGE_EXT = "whl"

