SUMMARY = "Python module to support running any existing function with a given timeout."
HOMEPAGE = "https://github.com/kata198/func_timeout"
SECTION = "devel/python"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=e6a600fd5e1d9cbde2d983680233ad02"

PYPI_SRC_URI = "https://files.pythonhosted.org/packages/b3/0d/bf0567477f7281d9a3926c582bfef21bff7498fc0ffd3e9de21811896a0b/func_timeout-4.3.5.tar.gz"
PYPI_PACKAGE = "func_timeout"

SRC_URI[md5sum] = "3535d4e00d54e36757ba7c65f20e4c91"
SRC_URI[sha256sum] = "74cd3c428ec94f4edfba81f9b2f14904846d5ffccc27c92433b8b5939b5575dd"

inherit pypi


