SUMMARY = "Extended Type Hinting Support"
DESCRIPTION = " \
* Functions for thorough checks on types \
* Instance checks considering generics \
* Typesafe Duck-typing \"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=de6d7dd24be15cc00bdfd9714f4929b3"

PYPI_SRC_URI = "https://github.com/ramonhagenaars/typish/archive/v1.9.1.tar.gz"

SRC_URI[md5sum] = "137b900c26363230da99416d12540fe2"
SRC_URI[sha256sum] = "d0f8e0dc2161fbe24fba50177e1beaa29d9b811d6374fdcc5af48dd4a5b135db"

inherit pypi

